//! Build script: embeds the elevation manifest (per-machine install needs admin),
//! generates the per-app config (env-overridable; defaults to C0PL4ND for local
//! dev), and embeds the app payload archive (the compiled app + assets, zipped).
use std::{env, fs, path::PathBuf};

fn env_or(key: &str, default: &str) -> String {
    env::var(key).unwrap_or_else(|_| default.to_string())
}

fn main() {
    // --- elevation manifest (requireAdministrator) on Windows targets ---
    #[cfg(windows)]
    {
        use embed_manifest::{embed_manifest, manifest::ExecutionLevel, new_manifest};
        // ITASHA_NO_ELEVATE=1 builds a non-elevated test exe (visual QA without UAC).
        if std::env::var_os("CARGO_CFG_WINDOWS").is_some()
            && std::env::var_os("ITASHA_NO_ELEVATE").is_none()
        {
            embed_manifest(
                new_manifest("ItashaCorp.Installer")
                    .requested_execution_level(ExecutionLevel::RequireAdministrator),
            )
            .expect("failed to embed elevation manifest");
        }
    }

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- per-app config (generated consts) ---
    let cfg = format!(
        "// @generated by build.rs\n\
         pub const APP_NAME: &str = {:?};\n\
         pub const APP_BIN: &str = {:?};\n\
         pub const VENDOR: &str = {:?};\n\
         pub const INSTALL_SUBDIR: &str = {:?};\n\
         pub const VERSION: &str = {:?};\n\
         pub const PUBLISHER: &str = {:?};\n\
         pub const HOMEPAGE: &str = {:?};\n\
         pub const TAGLINE: &str = {:?};\n\
         pub const KANJI: &str = {:?};\n\
         pub const VOICE_HEX: &str = {:?};\n",
        env_or("ITASHA_APP_NAME", "C0PL4ND"),
        env_or("ITASHA_APP_BIN", "c0pl4nd.exe"),
        env_or("ITASHA_VENDOR", "Itasha.Corp"),
        env_or("ITASHA_INSTALL_SUBDIR", "C0PL4ND"),
        env_or("ITASHA_VERSION", "0.0.0"),
        env_or("ITASHA_PUBLISHER", "Itasha.Corp"),
        env_or("ITASHA_HOMEPAGE", "https://github.com/itasha-corp/c0pl4nd"),
        env_or(
            "ITASHA_TAGLINE",
            "The operator's shell into the wired.",
        ),
        env_or("ITASHA_KANJI", "端末"),
        // Per-app voice color (the banner/brand accent). C0PL4ND violet by default.
        env_or("ITASHA_VOICE_HEX", "#B48CE8"),
    );
    fs::write(out.join("app_config.rs"), cfg).unwrap();

    // --- payload archive (zip of the app dir). Real build sets ITASHA_PAYLOAD_ZIP;
    //     local dev gets a valid empty zip so include_bytes! compiles. ---
    let payload_dst = out.join("payload.zip");
    match env::var_os("ITASHA_PAYLOAD_ZIP") {
        Some(src) => {
            fs::copy(&src, &payload_dst).expect("failed to copy ITASHA_PAYLOAD_ZIP");
        }
        None => {
            // minimal valid empty ZIP (End-Of-Central-Directory record only)
            const EMPTY_ZIP: [u8; 22] = [
                0x50, 0x4b, 0x05, 0x06, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            ];
            fs::write(&payload_dst, EMPTY_ZIP).unwrap();
        }
    }

    for k in [
        "ITASHA_PAYLOAD_ZIP",
        "ITASHA_APP_NAME",
        "ITASHA_APP_BIN",
        "ITASHA_VENDOR",
        "ITASHA_INSTALL_SUBDIR",
        "ITASHA_VERSION",
        "ITASHA_PUBLISHER",
        "ITASHA_HOMEPAGE",
        "ITASHA_TAGLINE",
        "ITASHA_KANJI",
        "ITASHA_VOICE_HEX",
        "ITASHA_NO_ELEVATE",
    ] {
        println!("cargo:rerun-if-env-changed={k}");
    }
}
